import './global.css';
import Provider from '../config/provider';
import { Header } from '@final/component';
export const metadata = {
  title: 'Welcome to lms',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="md:container md:mx-auto px-5 md:px-14 bg-[#FAFAFA] min:h-screen">
            <Header />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
